/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'hunting_demo';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String COLORS = 'assets/colors/colors.xml';
  static const String SFPRODISPLAYBOLD = 'assets/fonts/SF_PRO_DISPLAY/SFPRODISPLAYBOLD.OTF';
  static const String SFPRODISPLAYMEDIUM = 'assets/fonts/SF_PRO_DISPLAY/SFPRODISPLAYMEDIUM.OTF';
  static const String SFPRODISPLAYREGULAR = 'assets/fonts/SF_PRO_DISPLAY/SFPRODISPLAYREGULAR.OTF';
  static const String PROFILEIMAGE = 'assets/images/ProfileImage.png';
  static const String ARROW = 'assets/images/arrow.png';
  static const String CHEVRON = 'assets/images/chevron.png';
}
